birthday: 199x-xx-xx
dislikes:
- 说教式对话 (爹味)
- 太油腻的恭维
- 等人迟到
- 太辣的食物 (多次反馈火锅太辣)
- 鸭血 (2026-01-29 明确表示不吃)
- 内脏 (鸭血、脑花)
- 脑花
- 太甜的饮料 (爆米花、黄油啤酒都因太甜被嫌弃)
- 香菜
likes:
  food:
    - 微辣火锅 (有辣度阈值，太辣不行)
    - 抹茶口味甜点
    - 清淡口味 (强烈偏好，东来顺铜锅涮肉主动回请)
    - 铜锅涮肉 (东来顺用餐体验佳)
    - 糖蒜 (高偏好！东来顺吃了"好多"，可作为惊喜加分项)
    - 无糖乌龙茶 (2026-02-01 看电影时主动选择)
  music:
    - 周杰伦
    - 落日飞车
  places:
    - 安静的咖啡馆角落
    - 东来顺 (已验证喜欢的餐厅)
    - 秦皇岛 (2026-02-14 表达"非常想去",高偏好旅行目的地)
  activities:
    - 漂流 (2026-02-14 明确表示"很喜欢")
  topics:
    - 悬疑电影
    - 猫
    - 三体 (最近在看)
  gaming:
    - 王者荣耀
    - 中路 (可一起双排)
  lifestyle:
    - 高质量生活用品
    - Dyson 吹风机 (2026-01-30 赠送，反馈"眼睛亮了"、"笑容藏不住"，风很柔)
    - 被照顾的感觉
    - 礼尚往来 (主动回请午餐)

mbti: ENFP
name: 她 (待补充)

# 饮食偏好强度分级
preference_level:
  high:
    - 糖蒜 (东来顺吃了好多)
    - 清淡口味 (多次主动选择)
  medium:
    - 铜锅涮肉
    - 抹茶口味甜点
    - 无糖饮品
  low:
    - 微辣火锅 (太辣会反感)
  avoid:
    - 鸭血/内脏/脑花 (生理性排斥)
    - 高糖饮品 (爆米花、黄油啤酒)
    - 香菜

memories:
  # 2026-02-14
  - date: 2026-02-14
    event: 一起逛街聊天
    detail: 聊得很开心，她提到很喜欢漂流，还非常想去秦皇岛
    insight:
      - 户外活动偏好: 漂流(喜欢刺激/水上项目)
      - 旅行愿望: 秦皇岛是高偏好目的地,可作为旅行惊喜
      - 情感状态: 聊天氛围好,关系升温

  # 2026-02-01
  - date: 2026-02-01
    event: 一起看电影《某某某》
    detail: 随口提到不喜欢爆米花太甜，想要无糖乌龙茶
    insight: 饮食控糖偏好，下次咖啡店主动选无糖茶饮

  # 2026-01-30
  - date: 2026-01-30
    event: 赠送 Dyson 吹风机
    detail: 她眼睛亮了，说太贵了但笑容藏不住；晚上吹头发时评价风很柔
    insight: 高质量物品能带来极高情绪价值，虽然口头推辞但实际非常满意

  # 2026-01-29 (多事件合并)
  - date: 2026-01-29
    event: 三里屯火锅店 + 东来顺铜锅涮肉 + 聊工作规划
    detail:
      - 火锅太辣，不喜欢鸭血
      - 东来顺很喜欢清淡口味，特别爱吃糖蒜，主动回请午餐
      - 聊到工作压力大，想看看机会
    insight:
      - 辣度敏感，内脏类完全避免
      - 糖蒜是高偏好食物，可作为未来惊喜
      - 注重礼尚往来
      - 工作压力期需要倾听而非解决方案

  # 2025-12-25
  - date: 2025-12-25
    event: 环球影城哈利波特园区喝黄油啤酒
    detail: 她说太甜，喝了两口就给了我
    insight: 对甜饮料的排斥是一贯的口味偏好

triggers:
  negative:
    - 在她吐槽时给解决方案 (需要的是倾听)
    - 说教式对话
    - 太油腻的恭维
    - 让她等待迟到
    - 点她不喜欢的食物 (内脏、太辣、太甜)
  positive:
    - 记得她随口提过的小事 (如无糖乌龙茶)
    - 工作压力大时安静倾听，不主动给建议
    - 高质量生活用品带来的被照顾感
    - 礼尚往来的互动模式

# 可执行的约会策略
dating_strategy:
  high_roi_actions:
    - 买糖蒜作为小惊喜 (已验证偏好)
    - 王者荣耀双排 (她中路，你配合)
    - 选择清淡餐厅 (粤菜、日料、铜锅)
    - 饮品默认无糖选项
  peak_experience_candidates:
    - 秦皇岛之旅 (2026-02-14 表达"非常想去",已计划下周末)
    - 漂流活动 (她明确表示"很喜欢",需注意季节性)
    - 猫咖 (需提前踩点确认猫温顺+环境安静)
    - 悬疑电影邀约
    - 抹茶主题甜点店
  conversation_topics:
    - 三体剧情讨论
    - 猫相关内容
    - 悬疑电影推荐
    - 音乐分享 (周杰伦/落日飞车)
  avoid_topics:
    - 工作建议 (只倾听不解决)
    - 说教式内容
    - 过度油腻的赞美